Docs: Add state diagram
UnBArqDsw2022-2/2022.2-G1 pull request #21
Opened 2022-12-04 15:17 UTC by fmaachadoo

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the CONTRIBUTING.md doc.
- [x] I have added necessary documentation (if appropriate).
- [ ] Any dependent changes have been merged and published in downstream modules.

## Further comments

https://docs.google.com/drawings/d/1ajhehrDmPNijGB0AewbvrBhfsAaaI7hIa_H4vA2TyQg/edit?usp=sharing

2022-12-04 23:32 UTC, Sabanai104 requested changes
Falta adicionar a página documentando esse diagrama. De resto boa demais!

2022-12-05 23:37 UTC, Sabanai104 requested changes
Algumas ações da "página de bebida" e da "página de Perfil"só são possíveis com Login também, talvez seja interessante representa-las.

2022-12-05 23:37 UTC, Sabanai104 commented on docs/Modelagem/2.1.2.1.DiagramaDeEstados.md
> +
Só isso? Eu tenho certeza que tem mais sobre o diagrama de estado. Além disso, fale um pouco sobre a metodologia do mesmo também, falar o que são os estados e assim por diante. Imagine que esse documento é para explicar para uma pessoa que simplesmente não conhece nada.

2022-12-06 02:45 UTC, PhRezende-eng approved these changes

2022-12-06 03:11 UTC, merged